defaults: &defaults
  OAuth2:
    client_id: Q0CXOKZOGGE1eShZp61Q8nSBFHcI3nvAB1XrHsbxPybDjkuR6o
    client_secret: hp1ZgVlgWC1SqRGz8ZPK05kbceRCjxMeV9iZleXt
  Constant:
    baseURL: https://appcenter.intuit.com/connect/oauth2
    tokenURL: https://oauth.platform.intuit.com/oauth2/v1/tokens/bearer
    scope: com.intuit.quickbooks.accounting
    resfresh_grant_type: refresh_token
    response_type: code
    grant_type: authorization_code
  Settings:
    host_uri: http://quickbooks.dev:3000/
    redirect_uri: http://quickbooks.dev:3000/token/new
    state: randomState

development:
  <<: *defaults

production:
  <<: *defaults
  OAuth2:
    client_id: <%= ENV['CLIENT_ID'] %>
    client_secret: <%= ENV['CLIENT_SECRET'] %>
  Settings:
    host_uri: <%= ENV['HOST_URL'] %>
    redirect_uri: <%= ENV['REDIRECT_URL'] %>
